spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 单个Nacos服务器地址，用于服务注册
        namespace: 命名空间ID # 如果使用的是Nacos的命名空间功能，需要配置此项
        cluster-name: 集群名称 # 如果需要指定集群，在这里配置
      config:
        server-addr: 127.0.0.1:8848 # 单个Nacos服务器地址，用于配置中心
        namespace: 命名空间ID # 如果使用的是Nacos的命名空间功能，需要配置此项
        cluster-name: 集群名称 # 如果需要指定集群，在这里配置
        shared-configs:
          - data-id: shared-config.properties # 共享配置文件的dataId
            group: DEFAULT_GROUP # 配置分组，默认是DEFAULT_GROUP
            refresh: true # 是否自动刷新配置


logging:
  config: classpath:log4j2-prod.xml