#阿波罗AppID
app:
  id: car-hailding

server:
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  application:
    name: car-hailding
  profiles:
    active: sit
  messages:
    basename: i18n/messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: izW5(WVM(P3svnB06
    url: jdbc:mysql://w-bzrds-692a4582a25b4933visz.service.testdb:3306/db_scanner_application_sit?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: scanner_application_sit
  elasticsearch:
    rest:
      uris: http://10.90.85.55:9200,http://10.90.85.38:9200,http://10.90.85.47:9200
logging:
  config: classpath:log4j2-${spring.profiles.active}.xml

mybatis-plus:
  # 全局配置文件位置（可选）
#  config-location: classpath:mybatis/mybatis-config.xml
  # Mapper XML文件位置
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  # 配置实体类所在的包名，MyBatis-Plus会自动扫描并注册为别名
  type-aliases-package: com.car.hailing.entity
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    # 允许在resultType="map"时映射null值
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用(包括执行结果)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    use-column-label: true
    auto-mapping-behavior: full
    default-statement-timeout: 25000
  # 全局配置
  global-config:
    # 配置表前缀
    db-config:
      # 主键类型 AUTO:"数据库ID自增"
      # INPUT:"用户输入ID",
      # ID_WORKER:"全局唯一ID (数字类型唯一ID)",
      # UUID:"全局唯一ID UUID";
      id-type: auto
      # 开启驼峰命名规则转换
      # capital-mode: true
      # 配置逻辑删除相关属性
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 分页插件配置
  pagination:
    enabled: true
    page-size: 10
    reasonable: true


management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: info,health,prometheus
  metrics:
    export:
      prometheus:
        histogram-flavor: Prometheus
    tags:
      AppName: ${APPNAME}
      ProjName: ${PROJNAME}
      application: ${spring.application.name}
      namespace: ${spring.profiles.active}
      project: ${PROJNAME}
    web:
      server:
        request:
          autotime:
            percentiles: 0.90,0.95,0.99


#http配置服务
http:
  maxTotal: 100 #最大连接数
  defaultMaxPerRoute : 20 #并发数
  connectTimeout: 1000 #创建连接的最长时间
  connectionRequestTimeout: 500 #从连接池中获取到连接的最长时间
  socketTimeout: 10000 #数据传输的最长时间
  staleConnectionCheckEnabled: true #提交请求前测试连接是否可用


